import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { LayoutGrid, Ruler, Sparkles, Armchair, Wallet, Download } from 'lucide-react';

const TABS = [
  { id: 'plans', label: 'Floor plans', icon: LayoutGrid, img: '/assets/samples/empty_room.png',
    caption: 'Vector floor plans generated from a single walkthrough.', stat: '5 rooms detected' },
  { id: 'measure', label: 'Measurements', icon: Ruler, img: '/assets/samples/7.jpg',
    caption: 'Wall, room and ceiling dimensions with area totals.', stat: '±1.2 cm accuracy' },
  { id: 'design', label: 'AI design', icon: Sparkles, img: '/assets/samples/styled_room.png',
    caption: 'Photoreal concepts generated by Mantha AI.', stat: '3 variations' },
  { id: 'layout', label: 'Furniture layout', icon: Armchair, img: '/assets/samples/1.jpg',
    caption: 'Scale-accurate placement with clearance checks.', stat: '11 items placed' },
  { id: 'budget', label: 'Budget report', icon: Wallet, img: '/assets/samples/5.jpg',
    caption: 'Itemised costing with live shopping links.', stat: '₹1.84L total' },
  { id: 'export', label: 'Exports', icon: Download, img: '/assets/samples/9.jpg',
    caption: 'PDF, SVG and CAD-ready output in one click.', stat: 'PDF · SVG · DWG' },
];

/** Animated product showcase with live-switching tabs. */
export function ShowcaseTabs() {
  const [active, setActive] = useState(0);
  const t = TABS[active];

  return (
    <div>
      <div className="mb-8 flex flex-wrap justify-center gap-2">
        {TABS.map((tab, i) => {
          const Icon = tab.icon;
          const on = active === i;
          return (
            <button
              key={tab.id}
              onClick={() => setActive(i)}
              className={`relative flex items-center gap-2 rounded-full px-4 py-2.5 text-[13px] font-medium transition-colors duration-300 ${
                on ? 'text-foreground' : 'text-foreground/50 hover:text-foreground/70'
              }`}
            >
              {on && (
                <motion.span
                  layoutId="showcase-pill"
                  className="absolute inset-0 rounded-full border border-primary/35 bg-primary/12"
                  transition={{ type: 'spring', stiffness: 320, damping: 30 }}
                />
              )}
              <Icon className="relative h-3.5 w-3.5" />
              <span className="relative">{tab.label}</span>
            </button>
          );
        })}
      </div>

      <div className="relative overflow-hidden rounded-[24px] border border-foreground/[0.10] bg-white/70 backdrop-blur-2xl">
        <div className="relative aspect-[16/9]">
          <AnimatePresence mode="wait">
            <motion.img
              key={t.id}
              src={t.img}
              alt={t.label}
              initial={{ opacity: 0, scale: 1.04, filter: 'blur(10px)' }}
              animate={{ opacity: 1, scale: 1, filter: 'blur(0px)' }}
              exit={{ opacity: 0, scale: 0.99 }}
              transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
              className="absolute inset-0 h-full w-full object-cover"
            />
          </AnimatePresence>
          <div className="absolute inset-0 bg-gradient-to-t from-background via-background/25 to-transparent" />

          <motion.div
            key={`${t.id}-meta`}
            initial={{ opacity: 0, y: 14 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.55, delay: 0.12 }}
            className="absolute bottom-6 left-6 right-6 flex flex-wrap items-end justify-between gap-4"
          >
            <div>
              <p className="text-[10px] font-medium uppercase tracking-[0.18em] text-primary">{t.label}</p>
              <p className="mt-1.5 max-w-md text-[15px] text-foreground/85">{t.caption}</p>
            </div>
            <span className="rounded-full border border-foreground/15 bg-black/35 px-4 py-2 text-[12px] font-medium text-foreground/80 backdrop-blur-md">
              {t.stat}
            </span>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
